/*
Navicat MySQL Data Transfer

Source Server         : mcstats
Source Server Version : 50531
Source Host           : 10.10.1.50:3306
Source Database       : metrics

Target Server Type    : MYSQL
Target Server Version : 50531
File Encoding         : 65001

Date: 2013-09-23 23:20:18
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Records of Country
-- ----------------------------
INSERT INTO `Country` VALUES ('AD', 'Andorra');
INSERT INTO `Country` VALUES ('AE', 'United Arab Emirates');
INSERT INTO `Country` VALUES ('AF', 'Afghanistan');
INSERT INTO `Country` VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO `Country` VALUES ('AI', 'Anguilla');
INSERT INTO `Country` VALUES ('AL', 'Albania');
INSERT INTO `Country` VALUES ('AM', 'Armenia');
INSERT INTO `Country` VALUES ('AO', 'Angola');
INSERT INTO `Country` VALUES ('AQ', 'Antarctica');
INSERT INTO `Country` VALUES ('AR', 'Argentina');
INSERT INTO `Country` VALUES ('AS', 'American Samoa');
INSERT INTO `Country` VALUES ('AT', 'Austria');
INSERT INTO `Country` VALUES ('AU', 'Australia');
INSERT INTO `Country` VALUES ('AW', 'Aruba');
INSERT INTO `Country` VALUES ('AZ', 'Azerbaijan');
INSERT INTO `Country` VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO `Country` VALUES ('BB', 'Barbados');
INSERT INTO `Country` VALUES ('BD', 'Bangladesh');
INSERT INTO `Country` VALUES ('BE', 'Belgium');
INSERT INTO `Country` VALUES ('BF', 'Burkina Faso');
INSERT INTO `Country` VALUES ('BG', 'Bulgaria');
INSERT INTO `Country` VALUES ('BH', 'Bahrain');
INSERT INTO `Country` VALUES ('BI', 'Burundi');
INSERT INTO `Country` VALUES ('BJ', 'Benin');
INSERT INTO `Country` VALUES ('BL', 'Saint BarthÃ©lemy');
INSERT INTO `Country` VALUES ('BM', 'Bermuda');
INSERT INTO `Country` VALUES ('BN', 'Brunei');
INSERT INTO `Country` VALUES ('BO', 'Bolivia');
INSERT INTO `Country` VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO `Country` VALUES ('BR', 'Brazil');
INSERT INTO `Country` VALUES ('BS', 'The Bahamas');
INSERT INTO `Country` VALUES ('BT', 'Bhutan');
INSERT INTO `Country` VALUES ('BV', 'Bouvet Island');
INSERT INTO `Country` VALUES ('BW', 'Botswana');
INSERT INTO `Country` VALUES ('BY', 'Belarus');
INSERT INTO `Country` VALUES ('BZ', 'Belize');
INSERT INTO `Country` VALUES ('CA', 'Canada');
INSERT INTO `Country` VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO `Country` VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO `Country` VALUES ('CF', 'Central African Republic');
INSERT INTO `Country` VALUES ('CG', 'Republic of the Congo');
INSERT INTO `Country` VALUES ('CH', 'Switzerland');
INSERT INTO `Country` VALUES ('CK', 'Cook Islands');
INSERT INTO `Country` VALUES ('CL', 'Chile');
INSERT INTO `Country` VALUES ('CM', 'Cameroon');
INSERT INTO `Country` VALUES ('CN', 'China');
INSERT INTO `Country` VALUES ('CO', 'Colombia');
INSERT INTO `Country` VALUES ('CR', 'Costa Rica');
INSERT INTO `Country` VALUES ('CU', 'Cuba');
INSERT INTO `Country` VALUES ('CV', 'Cape Verde');
INSERT INTO `Country` VALUES ('CW', 'CuraÃ§ao');
INSERT INTO `Country` VALUES ('CX', 'Christmas Island');
INSERT INTO `Country` VALUES ('CY', 'Cyprus');
INSERT INTO `Country` VALUES ('CZ', 'Czech Republic');
INSERT INTO `Country` VALUES ('DE', 'Germany');
INSERT INTO `Country` VALUES ('DJ', 'Djibouti');
INSERT INTO `Country` VALUES ('DK', 'Denmark');
INSERT INTO `Country` VALUES ('DM', 'Dominica');
INSERT INTO `Country` VALUES ('DO', 'Dominican Republic');
INSERT INTO `Country` VALUES ('DZ', 'Algeria');
INSERT INTO `Country` VALUES ('EC', 'Ecuador');
INSERT INTO `Country` VALUES ('EE', 'Estonia');
INSERT INTO `Country` VALUES ('EG', 'Egypt');
INSERT INTO `Country` VALUES ('EH', 'Western Sahara');
INSERT INTO `Country` VALUES ('ER', 'Eritrea');
INSERT INTO `Country` VALUES ('ES', 'Spain');
INSERT INTO `Country` VALUES ('ET', 'Ethiopia');
INSERT INTO `Country` VALUES ('FI', 'Finland');
INSERT INTO `Country` VALUES ('FJ', 'Fiji');
INSERT INTO `Country` VALUES ('FK', 'Falkland Islands');
INSERT INTO `Country` VALUES ('FM', 'Federated States of Micronesia');
INSERT INTO `Country` VALUES ('FO', 'Faroe Islands');
INSERT INTO `Country` VALUES ('FR', 'France');
INSERT INTO `Country` VALUES ('GA', 'Gabon');
INSERT INTO `Country` VALUES ('GB', 'United Kingdom');
INSERT INTO `Country` VALUES ('GD', 'Grenada');
INSERT INTO `Country` VALUES ('GE', 'Georgia');
INSERT INTO `Country` VALUES ('GF', 'French Guiana');
INSERT INTO `Country` VALUES ('GG', 'Guernsey');
INSERT INTO `Country` VALUES ('GH', 'Ghana');
INSERT INTO `Country` VALUES ('GI', 'Gibraltar');
INSERT INTO `Country` VALUES ('GL', 'Greenland');
INSERT INTO `Country` VALUES ('GM', 'The Gambia');
INSERT INTO `Country` VALUES ('GN', 'Guinea');
INSERT INTO `Country` VALUES ('GP', 'Guadeloupe');
INSERT INTO `Country` VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO `Country` VALUES ('GR', 'Greece');
INSERT INTO `Country` VALUES ('GS', 'South Georgia and the South Sandwich Isl');
INSERT INTO `Country` VALUES ('GT', 'Guatemala');
INSERT INTO `Country` VALUES ('GU', 'Guam');
INSERT INTO `Country` VALUES ('GY', 'Guyana');
INSERT INTO `Country` VALUES ('HK', 'Hong Kong');
INSERT INTO `Country` VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO `Country` VALUES ('HN', 'Honduras');
INSERT INTO `Country` VALUES ('HR', 'Croatia');
INSERT INTO `Country` VALUES ('HT', 'Haiti');
INSERT INTO `Country` VALUES ('HU', 'Hungary');
INSERT INTO `Country` VALUES ('ID', 'Indonesia');
INSERT INTO `Country` VALUES ('IE', 'Ireland');
INSERT INTO `Country` VALUES ('IL', 'Israel');
INSERT INTO `Country` VALUES ('IM', 'Isle of Man');
INSERT INTO `Country` VALUES ('IN', 'India');
INSERT INTO `Country` VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO `Country` VALUES ('IQ', 'Iraq');
INSERT INTO `Country` VALUES ('IR', 'Iran');
INSERT INTO `Country` VALUES ('IS', 'Iceland');
INSERT INTO `Country` VALUES ('IT', 'Italy');
INSERT INTO `Country` VALUES ('JE', 'Jersey');
INSERT INTO `Country` VALUES ('JM', 'Jamaica');
INSERT INTO `Country` VALUES ('JO', 'Jordan');
INSERT INTO `Country` VALUES ('JP', 'Japan');
INSERT INTO `Country` VALUES ('KE', 'Kenya');
INSERT INTO `Country` VALUES ('KG', 'Kyrgyzstan');
INSERT INTO `Country` VALUES ('KH', 'Cambodia');
INSERT INTO `Country` VALUES ('KI', 'Kiribati');
INSERT INTO `Country` VALUES ('KM', 'Comoros');
INSERT INTO `Country` VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO `Country` VALUES ('KP', 'North Korea');
INSERT INTO `Country` VALUES ('KR', 'South Korea');
INSERT INTO `Country` VALUES ('KW', 'Kuwait');
INSERT INTO `Country` VALUES ('KY', 'Cayman Islands');
INSERT INTO `Country` VALUES ('KZ', 'Kazakhstan');
INSERT INTO `Country` VALUES ('LA', 'Laos');
INSERT INTO `Country` VALUES ('LB', 'Lebanon');
INSERT INTO `Country` VALUES ('LC', 'Saint Lucia');
INSERT INTO `Country` VALUES ('LI', 'Liechtenstein');
INSERT INTO `Country` VALUES ('LK', 'Sri Lanka');
INSERT INTO `Country` VALUES ('LR', 'Liberia');
INSERT INTO `Country` VALUES ('LS', 'Lesotho');
INSERT INTO `Country` VALUES ('LT', 'Lithuania');
INSERT INTO `Country` VALUES ('LU', 'Luxembourg');
INSERT INTO `Country` VALUES ('LV', 'Latvia');
INSERT INTO `Country` VALUES ('LY', 'Libya');
INSERT INTO `Country` VALUES ('MA', 'Morocco');
INSERT INTO `Country` VALUES ('MC', 'Monaco');
INSERT INTO `Country` VALUES ('MD', 'Moldova');
INSERT INTO `Country` VALUES ('ME', 'Montenegro');
INSERT INTO `Country` VALUES ('MF', 'Collectivity of Saint Martin');
INSERT INTO `Country` VALUES ('MG', 'Madagascar');
INSERT INTO `Country` VALUES ('MH', 'Marshall Islands');
INSERT INTO `Country` VALUES ('MK', 'Republic of Macedonia');
INSERT INTO `Country` VALUES ('ML', 'Mali');
INSERT INTO `Country` VALUES ('MM', 'Myanmar');
INSERT INTO `Country` VALUES ('MN', 'Mongolia');
INSERT INTO `Country` VALUES ('MO', 'Macau');
INSERT INTO `Country` VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO `Country` VALUES ('MQ', 'Martinique');
INSERT INTO `Country` VALUES ('MR', 'Mauritania');
INSERT INTO `Country` VALUES ('MS', 'Montserrat');
INSERT INTO `Country` VALUES ('MT', 'Malta');
INSERT INTO `Country` VALUES ('MU', 'Mauritius');
INSERT INTO `Country` VALUES ('MV', 'Maldives');
INSERT INTO `Country` VALUES ('MW', 'Malawi');
INSERT INTO `Country` VALUES ('MX', 'Mexico');
INSERT INTO `Country` VALUES ('MY', 'Malaysia');
INSERT INTO `Country` VALUES ('MZ', 'Mozambique');
INSERT INTO `Country` VALUES ('NA', 'Namibia');
INSERT INTO `Country` VALUES ('NC', 'New Caledonia');
INSERT INTO `Country` VALUES ('NE', 'Niger');
INSERT INTO `Country` VALUES ('NF', 'Norfolk Island');
INSERT INTO `Country` VALUES ('NG', 'Nigeria');
INSERT INTO `Country` VALUES ('NI', 'Nicaragua');
INSERT INTO `Country` VALUES ('NL', 'Netherlands');
INSERT INTO `Country` VALUES ('NO', 'Norway');
INSERT INTO `Country` VALUES ('NP', 'Nepal');
INSERT INTO `Country` VALUES ('NR', 'Nauru');
INSERT INTO `Country` VALUES ('NU', 'Niue');
INSERT INTO `Country` VALUES ('NZ', 'New Zealand');
INSERT INTO `Country` VALUES ('OM', 'Oman');
INSERT INTO `Country` VALUES ('PA', 'Panama');
INSERT INTO `Country` VALUES ('PE', 'Peru');
INSERT INTO `Country` VALUES ('PF', 'French Polynesia');
INSERT INTO `Country` VALUES ('PG', 'Papua New Guinea');
INSERT INTO `Country` VALUES ('PH', 'Philippines');
INSERT INTO `Country` VALUES ('PK', 'Pakistan');
INSERT INTO `Country` VALUES ('PL', 'Poland');
INSERT INTO `Country` VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO `Country` VALUES ('PN', 'Pitcairn Islands');
INSERT INTO `Country` VALUES ('PR', 'Puerto Rico');
INSERT INTO `Country` VALUES ('PS', 'State of Palestine');
INSERT INTO `Country` VALUES ('PT', 'Portugal');
INSERT INTO `Country` VALUES ('PW', 'Palau');
INSERT INTO `Country` VALUES ('PY', 'Paraguay');
INSERT INTO `Country` VALUES ('QA', 'Qatar');
INSERT INTO `Country` VALUES ('RO', 'Romania');
INSERT INTO `Country` VALUES ('RS', 'Serbia');
INSERT INTO `Country` VALUES ('RU', 'Russia');
INSERT INTO `Country` VALUES ('RW', 'Rwanda');
INSERT INTO `Country` VALUES ('SA', 'Saudi Arabia');
INSERT INTO `Country` VALUES ('SB', 'Solomon Islands');
INSERT INTO `Country` VALUES ('SC', 'Seychelles');
INSERT INTO `Country` VALUES ('SD', 'Sudan');
INSERT INTO `Country` VALUES ('SE', 'Sweden');
INSERT INTO `Country` VALUES ('SG', 'Singapore');
INSERT INTO `Country` VALUES ('SH', 'Saint Helena');
INSERT INTO `Country` VALUES ('SI', 'Slovenia');
INSERT INTO `Country` VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO `Country` VALUES ('SK', 'Slovakia');
INSERT INTO `Country` VALUES ('SL', 'Sierra Leone');
INSERT INTO `Country` VALUES ('SM', 'San Marino');
INSERT INTO `Country` VALUES ('SN', 'Senegal');
INSERT INTO `Country` VALUES ('SO', 'Somalia');
INSERT INTO `Country` VALUES ('SR', 'Suriname');
INSERT INTO `Country` VALUES ('SS', 'South Sudan');
INSERT INTO `Country` VALUES ('SV', 'El Salvador');
INSERT INTO `Country` VALUES ('SX', 'Sint Maarten');
INSERT INTO `Country` VALUES ('SY', 'Syria');
INSERT INTO `Country` VALUES ('SZ', 'Swaziland');
INSERT INTO `Country` VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO `Country` VALUES ('TD', 'Chad');
INSERT INTO `Country` VALUES ('TF', 'French Southern and Antarctic Lands');
INSERT INTO `Country` VALUES ('TG', 'Togo');
INSERT INTO `Country` VALUES ('TH', 'Thailand');
INSERT INTO `Country` VALUES ('TJ', 'Tajikistan');
INSERT INTO `Country` VALUES ('TK', 'Tokelau');
INSERT INTO `Country` VALUES ('TM', 'Turkmenistan');
INSERT INTO `Country` VALUES ('TN', 'Tunisia');
INSERT INTO `Country` VALUES ('TO', 'Tonga');
INSERT INTO `Country` VALUES ('TR', 'Turkey');
INSERT INTO `Country` VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO `Country` VALUES ('TV', 'Tuvalu');
INSERT INTO `Country` VALUES ('TZ', 'Tanzania');
INSERT INTO `Country` VALUES ('UA', 'Ukraine');
INSERT INTO `Country` VALUES ('UG', 'Uganda');
INSERT INTO `Country` VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO `Country` VALUES ('US', 'United States');
INSERT INTO `Country` VALUES ('UY', 'Uruguay');
INSERT INTO `Country` VALUES ('UZ', 'Uzbekistan');
INSERT INTO `Country` VALUES ('VA', 'Vatican City');
INSERT INTO `Country` VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO `Country` VALUES ('VE', 'Venezuela');
INSERT INTO `Country` VALUES ('VG', 'British Virgin Islands');
INSERT INTO `Country` VALUES ('VU', 'Vanuatu');
INSERT INTO `Country` VALUES ('WF', 'Wallis and Futuna');
INSERT INTO `Country` VALUES ('WS', 'Samoa');
INSERT INTO `Country` VALUES ('YE', 'Yemen');
INSERT INTO `Country` VALUES ('YT', 'Mayotte');
INSERT INTO `Country` VALUES ('ZA', 'South Africa');
INSERT INTO `Country` VALUES ('ZM', 'Zambia');
INSERT INTO `Country` VALUES ('ZW', 'Zimbabwe');
